import os

# window setting
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

# player settings
PLAYER_SIZE = 80
PLAYER_SPEED = 5
PLAYER_SPRINT_SPEED = 6
PLAYER_ATTACK_ANIMATION_DURATION = 200


# spell settings
BULLET_SPEED = 12
BULLET_LIFETIME = 1000
SHOOT_COOLDOWN = 400

# audio settings

MUSIC_VOLUME = 0.0
SFX_VOLUME = 0.5

# ghost
GHOST_WIDTH = 60
GHOST_HEIGHT = 80

ICON_PATH = os.path.join("assets", "icon.png")
FPS = 60

UI_FONT_SIZE = 20
HEALTH_COLOR = (204, 23, 10)
ENERGY_COLOR = (5, 64, 227)
XP_COLOR = (235, 247, 0)

PLAYER_BASE_XP = 100
XP_MULTIPLIER = 1.75
STAT_BOOST_HP = 20
STAT_BOOST_ENERGY = 10
